---
- name: Remove Apache Web Server
  hosts: web_servers
  become: true
  tasks:
    - name: Stop apache service
      ansible.builtin.service:
        name: apache2
        state: stopped
    - name: Remove apache package
      ansible.builtin.apt:  # or ansible.builtin.apt for Debian systems
        name: apache2
        state: absent
    - name: Delete Apache configuration files (if any)
      ansible.builtin.file:
        path: /etc/apache2/
        state: absent
