---
- name: Install PHP on Ubuntu
  hosts: web_servers
  become: true
  tasks:
  # apt update
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: yes
  # apt upgrade
    - name: Upgrade packages
      ansible.builtin.apt:
        upgrade: yes
  # Install php
    - name: Install PHP and required extensions
      ansible.builtin.apt:
        name:
          - php
          - libapache2-mod-php
          - php-cli
          - php-fpm
          - php-mysql  # Add other PHP extensions as needed
        state: present
    - name: Enable PHP-FPM service
      ansible.builtin.service:
        name: php7.4-fpm  # Adjust the version if needed
        state: started
        enabled: yes
     - name: Install Apache
     # installing apache
      ansible.builtin.apt:
        name:
          - apache2
        state: present
     # Starting apache service
    - name: Start and Enable Apache service
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: yes
