---
- name: Install PHP on Ubuntu
  hosts: web_servers
  become: true
  tasks:
  # apt update
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: yes
  
  # apt upgrade
    - name: Upgrade packages
      ansible.builtin.apt:
        upgrade: yes


  # Install Software Properties common
    - name: Install software-properties-common
      ansible.builtin.apt:
        name:
          - software-properties-common
        state: present


  # https://launchpad.net/~ondrej/+archive/ubuntu/nginx
  # add the nginx repository
    - name: Add the PPA repository
      apt_repository:
        repo: "ppa:ondrej/nginx"
        state: present
  
  # https://launchpad.net/~ondrej/+archive/ubuntu/nginx
  # add the php repository
    - name: Add the PPA repository
      apt_repository:
        repo: "ppa:ondrej/php"
        state: present


 # apt update for nginx repository
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: yes
  
    - name: Upgrade the OS (apt-get dist-upgrade)
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes


    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: present

  # Starting apache service
    - name: Start and Enable nginx service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes


  # Install php
    - name: Install PHP and required extensions
      ansible.builtin.apt:
        name:
          - php8.3
          - php8.3-cli
          - php8.3-common
          - php8.3-fpm
          - php8.3-mysql
          - php8.3-gd
          - php8.3-curl
          - php8.3-xml
          - php8.3-mbstring
        state: present
  
  # Enable php-fpm
    - name: Enable PHP-FPM service
      ansible.builtin.service:
        name: php8.3-fpm  # Adjust the version if needed
        state: started
        enabled: yes

  # Restart nginx service after installing php
    - name: Restart the Apache HTTP server
      ansible.builtin.service:
        name: nginx
        state: restarted

  # Install unzip
    - name: Install unzip
      ansible.builtin.apt:
        name:
          - unzip
        state: present
