- name: Install mariadb on Ubuntu
  hosts: web_servers
  become: true
  tasks:
  # apt update
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: yes
  
  # apt upgrade
    - name: Upgrade packages
      ansible.builtin.apt:
        upgrade: yes
        

    - name: Install MariaDB packages
      ansible.builtin.apt:
        name:
          - mariadb-server
          - mariadb-client
        state: present

    - name: Start and enable MariaDB service
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes

    - name: Secure MariaDB installation
      ansible.builtin.mysql_user:
        name: root
        password: "{{ mariadb_root_password }}"
        host: localhost
        login_unix_socket: /var/run/mysqld/mysqld.sock
        state: present
      vars:
        mariadb_root_password: "kakarr"
